debug: true
environment: development #production, development
secret_key: secret_key
server:
  host: 0.0.0.0
  port: 8080

db:
  host: 0.0.0.0
  port: 5432
  username: admin
  password: password
  db_name: authn