debug: true
environment: development #production, development
jwt_secret_key: secret_key
jwt_access_token_expires: 60 #in minutes
server:
  host: 0.0.0.0
  port: 8080

db:
  host: 0.0.0.0
  port: 5432
  username: admin
  password: password
  db_name: authn