version: '3.7'


services:
  db:
    image: postgres:10.1
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authN
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./authN.sql:/docker-entrypoint-initdb.d/authN.sql
    ports:
      - 5432:5432